/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatList: typeof import('./../src/components/chat/list/index.vue')['default']
    ChatListItem: typeof import('./../src/components/chat/list/item.vue')['default']
    ChatSettings: typeof import('./../src/components/chat/settings.vue')['default']
    ChatTalk: typeof import('../src/pages/talk.vue')['default']
    ChatTalkItem: typeof import('./../src/components/chat/talk-item.vue')['default']
    ContentWrapper: typeof import('./../src/components/content-wrapper.vue')['default']
    FolderSettings: typeof import('../src/components/settings/folders.vue')['default']
    Greet: typeof import('./../src/components/Greet.vue')['default']
    LorebookHeader: typeof import('./../src/components/lorebook/header.vue')['default']
    LorebookList: typeof import('./../src/components/lorebook/list.vue')['default']
    LorebookListItem: typeof import('./../src/components/lorebook/list-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsFolders: typeof import('./../src/components/settings/folders.vue')['default']
    Sidebar: typeof import('./../src/components/sidebar/index.vue')['default']
    SidebarCollection: typeof import('./../src/components/sidebar/collection.vue')['default']
    SidebarCollectionsApp: typeof import('./../src/components/sidebar/collections/app.vue')['default']
    SidebarCollectionsContent: typeof import('./../src/components/sidebar/collections/content.vue')['default']
    SidebarItem: typeof import('./../src/components/sidebar/item.vue')['default']
    SidebarStatesApp: typeof import('./../src/components/sidebar/states/app.vue')['default']
    SidebarStatesToggle: typeof import('./../src/components/sidebar/states/toggle.vue')['default']
  }
}
