/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./../src/components/chat/index.vue')['default']
    ChatConversation: typeof import('./../src/components/chat/conversation.vue')['default']
    ChatList: typeof import('./../src/components/chat/list.vue')['default']
    ChatListItem: typeof import('./../src/components/chat/list-item.vue')['default']
    ChatTalk: typeof import('./../src/components/chat/talk.vue')['default']
    ChatTalkItem: typeof import('./../src/components/chat/talk-item.vue')['default']
    ContentWrapper: typeof import('./../src/components/content-wrapper.vue')['default']
    copy: typeof import('../src/components/sidebar/collections/app.vue')['default']
    Greet: typeof import('./../src/components/Greet.vue')['default']
    Lorebook: typeof import('./../src/components/lorebook/index.vue')['default']
    LorebookHeader: typeof import('./../src/components/lorebook/header.vue')['default']
    LorebookItem: typeof import('../src/components/lorebook/list-item.vue')['default']
    LorebookList: typeof import('./../src/components/lorebook/list.vue')['default']
    LorebookListItem: typeof import('./../src/components/lorebook/list-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/sidebar/index.vue')['default']
    SidebarAppState: typeof import('./../src/components/sidebar/app-state.vue')['default']
    SidebarCollection: typeof import('./../src/components/sidebar/collection.vue')['default']
    SidebarCollectionsApp: typeof import('./../src/components/sidebar/collections/app.vue')['default']
    SidebarCollectionsContent: typeof import('./../src/components/sidebar/collections/content.vue')['default']
    SidebarContentsChat: typeof import('./../src/components/sidebar/contents/chat.vue')['default']
    SidebarContentsFolder: typeof import('./../src/components/sidebar/contents/folder.vue')['default']
    SidebarFolderState: typeof import('../src/compone../src/components/sidebar/collections/app.vue')['default']
    SidebarItem: typeof import('./../src/components/sidebar/item.vue')['default']
    SidebarLinkState: typeof import('../src/components/sidebar/app-state.vue')['default']
    SidebarState: typeof import('./../src/components/sidebar/state.vue')['default']
    SidebarToggleState: typeof import('./../src/components/sidebar/toggle-state.vue')['default']
  }
}
